### ISSUE TITLE
It would be good to have a favicon

### ISSUE THREAD

**Issue by fcbond** [duoduo-lab/duoduo-lab.github.io#2]
I think you could use one of the symbols :-)

**Comment by duoduo-lab** [comment]
how does it look? :D

**Comment by fcbond** [comment]
Good in general but there is no favicon: https://en.wikipedia.org/wiki/Favicon

**Comment by duoduo-lab** [comment]
haha, understood, there is one, now :D

**Comment by fcbond** [comment]
it looks very nice.
